# Generated by Django 2.0.7 on 2018-08-09 10:15

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction, French Poetry etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pizz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pizzphoto', models.ImageField(height_field=100, help_text='Добавь пиццу', upload_to='', verbose_name=main.models.Basket, width_field=100)),
                ('aboutpizz', models.TextField(help_text='Состав пиццы', max_length=1000)),
            ],
        ),
    ]
