# Generated by Django 2.0.7 on 2018-08-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizz',
            name='title',
            field=models.CharField(help_text='Добавь фото пиццы', max_length=200),
        ),
    ]
