# Generated by Django 2.0.7 on 2018-08-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180809_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizz',
            name='pizzphoto',
            field=models.ImageField(help_text='Добавь фото', upload_to=''),
        ),
        migrations.AlterField(
            model_name='pizz',
            name='title',
            field=models.CharField(help_text='Добавь название', max_length=200),
        ),
    ]
