# Generated by Django 2.0.7 on 2018-08-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180809_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Добавь название', max_length=200)),
                ('drinkphoto', models.ImageField(help_text='Добавь фото', upload_to='')),
                ('price', models.CharField(help_text='Добавь цену', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='pizz',
            name='price',
            field=models.CharField(default=1, help_text='Добавь цену', max_length=200),
            preserve_default=False,
        ),
    ]
