# Generated by Django 2.0.7 on 2018-08-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180809_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Добавь название', max_length=200)),
                ('pastaphoto', models.ImageField(help_text='Добавь фото', upload_to='')),
                ('price', models.CharField(help_text='Добавь описание', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Potato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Добавь название', max_length=200)),
                ('potatophoto', models.ImageField(help_text='Добавь фото', upload_to='')),
                ('price', models.CharField(help_text='Добавь описание', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.CharField(help_text='Добавь описание', max_length=200),
        ),
    ]
